const String prmSecurity = '/prmSecurity';
const String studentSecurity = '/studentSecurity';
const String studentMore = '/studentMore';
const String studentMyCourses = '/studentMyCourses';
const String promoter = '/promoter';
const String sharedKey =
    'sharedKey=599cfFa931-?*234tjj%23-4287sEEd-847jj%23-3649%23165';

const String apiSignIn = '$studentSecurity/signIn';
const String apiForgetPassword = '$studentSecurity/forgotPassword';
const String apiPasswordConfirmCode = '$studentSecurity/passwordConfirmCode';
const String apiSetNewPassword = '$studentSecurity/setNewPassword';
const String apiPreSignUp = '$studentSecurity/preSignUp';
const String apiSignUp = '$studentSecurity/signUp';
const String apiHome = '/studentCourses/home';
const String apiAllCourses = '/studentCourses/allCourses';
const String apiLovs = '/general/lovs';
const String apiMyCourses = '$studentMyCourses/myCourses';
const String apiCourseDetails = '$studentMyCourses/courseDetails';
const String apiExamResult = '$studentMyCourses/examResult';
const String apiContinueAnyway = '$studentMyCourses/continueAnyway';
const String apiRetakeExam = '$studentMyCourses/retakeExam';
const String apiContactUs = '$studentMore/contactUs';
const String apiRefreshToken = '$studentSecurity/refreshToken';
const String apiNotification = '$studentMore/notifications';
const String apiProfile = '$studentMore/profile';
const String apiCompanyOffers = '$studentMore/companyOffers';
const String apiPrivateCourse = '$studentMore/privateCourses';
const String apiStudentCourseDetails = '/studentCourses/productDetails';
